### ISSUE TITLE
README in english

### ISSUE THREAD

**Issue by vityok** [sile/cl-dawg#3]
Hello,

while the sources are believed by some to be the best documentation and it is also possible to use Google translate on the existing README file, having it in English would be very welcome.

Please, consider making it the default readme for this repository.

With best regards

**Comment by sile** [comment]
Thanks for your advice.

I translated README to English at the commit https://github.com/sile/cl-dawg/commit/0ba5c224faee8c8818f33b7366b1a888bf9a8be5.

**Comment by vityok** [comment]
Thanks a lot! Despite being a somewhat niche library, it looks very well written and usable.

Happy New Year
